//! Icon mapping utilities

use egui_cha_ds::icons;

/// Get icon symbol from name
pub fn get_icon(name: &str) -> &'static str {
    match name.to_lowercase().as_str() {
        "house" | "home" => icons::HOUSE,
        "arrow_left" | "left" => icons::ARROW_LEFT,
        "arrow_right" | "right" => icons::ARROW_RIGHT,
        "plus" | "add" => icons::PLUS,
        "minus" => icons::MINUS,
        "x" | "close" => icons::X,
        "check" | "ok" => icons::CHECK,
        "gear" | "settings" | "config" => icons::GEAR,
        "info" => icons::INFO,
        "warning" | "warn" => icons::WARNING,
        "hash" => icons::HASH,
        "user" => icons::USER,
        "floppy_disk" | "save" => icons::FLOPPY_DISK,
        "trash" | "delete" => icons::TRASH,
        "pencil" | "edit" => icons::PENCIL_SIMPLE,
        "folder" => icons::FOLDER_SIMPLE,
        "file" => icons::FILE,
        "search" | "magnifying_glass" => icons::MAGNIFYING_GLASS,
        "refresh" | "reload" => icons::ARROWS_CLOCKWISE,
        "play" | "run" | "start" => icons::PLAY,
        "pause" => icons::PAUSE,
        "stop" => icons::STOP,
        "record" => icons::RECORD,
        "copy" => icons::COPY,
        "download" => icons::DOWNLOAD_SIMPLE,
        "upload" => icons::UPLOAD_SIMPLE,
        "link" => icons::LINK_SIMPLE,
        "eye" | "view" => icons::EYE,
        "eye_slash" | "hide" => icons::EYE_SLASH,
        "fire" | "hot" => icons::FIRE,
        "bug" | "debug" => icons::BUG,
        "wrench" | "tool" | "build" => icons::WRENCH,
        "x_circle" | "error" => icons::X_CIRCLE,
        "skull" | "danger" => icons::SKULL,
        "caret_up" | "up" => icons::CARET_UP,
        "caret_down" | "down" => icons::CARET_DOWN,
        "lock" => icons::LOCK,
        "lock_open" | "unlock" => icons::LOCK_OPEN,
        "maximize" => icons::CORNERS_OUT,
        "minimize" => icons::CORNERS_IN,
        "stack" | "layers" => icons::STACK,
        "sliders" => icons::SLIDERS_HORIZONTAL,
        "image" => icons::IMAGE,
        "monitor" | "display" => icons::MONITOR_PLAY,
        "grid" => icons::GRID_FOUR,
        "squares" => icons::SQUARES_FOUR,
        "broom" | "clean" => icons::BROOM,
        "zoom" | "zoom_in" => icons::MAGNIFYING_GLASS_PLUS,
        "frame" => icons::FRAME_CORNERS,
        "package" | "cube" => icons::STACK,
        "terminal" | "console" => icons::MONITOR_PLAY,
        "code" => icons::FILE,
        _ => icons::PLAY,
    }
}

/// Get list of available icon names for documentation
pub fn available_icons() -> Vec<&'static str> {
    vec![
        "play/run/start",
        "check/ok",
        "wrench/tool/build",
        "broom/clean",
        "pencil/edit",
        "trash/delete",
        "gear/settings",
        "bug/debug",
        "refresh/reload",
        "folder",
        "file",
        "plus/add",
        "minus",
        "x/close",
        "search",
        "copy",
        "download",
        "upload",
        "eye/view",
        "fire/hot",
        "lock",
        "unlock",
        "info",
        "warning",
        "stop",
        "pause",
        "home",
        "user",
        "terminal",
        "code",
        "package/cube",
    ]
}
